<?php

class tagdiv_block1_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_1'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block1_widget");'));

class tagdiv_block2_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_2'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block2_widget");'));

class tagdiv_block3_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_3'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block3_widget");'));

class tagdiv_block4_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_4'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block4_widget");'));
class tagdiv_block5_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_5'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block5_widget");'));

class tagdiv_block6_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_6'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block6_widget");'));

class tagdiv_block7_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_7'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block7_widget");'));
class tagdiv_block8_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_8'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block8_widget");'));

class tagdiv_block_ad_box_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_ad_box'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block_ad_box_widget");'));

class tagdiv_block_authors_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_authors'; // change only the block id, the rest is autogenerated
}

add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block_authors_widget");'));

class tagdiv_block_author_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_author'; // change only the block id, the rest is autogenerated
}

add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block_author_widget");'));

class tagdiv_block_popular_categories_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_popular_categories'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block_popular_categories_widget");'));

class tagdiv_block_instagram_widget extends tagdiv_block_widget {
    var $tagdiv_block_id = 'tagdiv_block_instagram'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("tagdiv_block_instagram_widget");'));