<?php

class Tagdiv_Block_1_Widget extends Tagdiv_Block_Widget {
    var $tagdiv_block_id = 'tagdiv_block_1'; // change only the block id, the rest is autogenerated
}
add_action('widgets_init', create_function('', 'return register_widget("Tagdiv_Block_1_Widget");'));
